import profiles from '@/data/bots.json';

/**
 * Per-bot identity: colour, glyph, and the story each one tells. Bots are named
 * by their slug everywhere -- there are no character names.
 *
 * The data lives in data/bots.json so the React app and the static prototype
 * read the same file and cannot drift. Range strings are generated by driving
 * all 169 hand classes through the compiled bots, not transcribed by hand.
 *
 * Colour is deliberately NOT the identifier. Validated against this surface,
 * eight categorical hues cannot be told apart reliably — and there are now more
 * bots than hues, so slots repeat. Every appearance carries glyph + name, with
 * colour as reinforcement only.
 */

export type GlyphName =
  | 'burst'
  | 'descend'
  | 'lock'
  | 'peak'
  | 'target'
  | 'die'
  | 'wall'
  | 'flag'
  | 'shield'
  | 'flame'
  | 'split'
  | 'key'
  | 'probe'
  | 'scales'
  | 'seat';

export type BotProfile = {
  slug: string;
  tagline: string;
  color: string;
  glyph: GlyphName;
  behaviour: string;
  story: string[];
  /** Shown in place of the record when the bot has never played. */
  unratedNote?: string;
  /** 169 chars, row-major from A down to 2; above the diagonal is suited. */
  range?: string;
  rangeLabel?: string;
  stats: { label: string; value: string }[];
};

export const BOT_PROFILES = profiles as unknown as Record<string, BotProfile>;

/* Roster order, straight from data/bots.json, which is curated by tier:
 * the shove family, then the street-local bots, then the archetypes. The
 * previous/next arrows on a bot page walk this, so it covers every bot
 * whether or not it has played a match yet. */
export const BOT_ORDER = Object.keys(BOT_PROFILES);

/*
 * One bot lives outside data/bots.json on purpose. It is in no listing, no
 * matrix and no roster count; the only way to reach it is to hold the next
 * arrow to the far end of the roster. Stepping back from the first bot skips
 * over it, so a single press of the other arrow does not give it away.
 */
export const SECRET_SLUG = 'secret';

export const SECRET_BOT: BotProfile = {
  slug: SECRET_SLUG,
  tagline: 'Not in the ledger.',
  color: '#241f1b',
  glyph: 'seat',
  behaviour: 'Unknown.',
  story: [
    'There is one seat this harness cannot fill.',
    'You have already played against it.',
  ],
  unratedNote: 'There is no record.',
  stats: [
    { label: 'Version', value: '—' },
    { label: 'Hands', value: '0' },
    { label: 'Seat', value: 'Occupied' },
  ],
};

export function botNeighbours(slug: string) {
  const count = BOT_ORDER.length;
  if (slug === SECRET_SLUG) {
    return {
      previous: BOT_ORDER[count - 1],
      next: BOT_ORDER[0],
      position: count + 1,
      count,
    };
  }
  const index = BOT_ORDER.indexOf(slug);
  if (index === -1) return { previous: null, next: null };
  return {
    /* The first bot steps back to the last real one, not to the secret. */
    previous: BOT_ORDER[(index - 1 + count) % count],
    next: index === count - 1 ? SECRET_SLUG : BOT_ORDER[index + 1],
    position: index + 1,
    count,
  };
}

export function botProfile(name: string): BotProfile | undefined {
  return BOT_PROFILES[name];
}

export const RANKS = 'AKQJT98765432';
