import profiles from '@/data/bots.json';
import dashboard from '@/data/dashboard.json';

/**
 * Per-bot identity: colour, glyph, and the story each one tells. Bots are named
 * by their slug everywhere -- there are no character names.
 *
 * The data lives in data/bots.json so the React app and the static prototype
 * read the same file and cannot drift. Range strings are generated by driving
 * all 169 hand classes through the compiled bots, not transcribed by hand.
 *
 * Colour is deliberately NOT the identifier. Validated against this surface,
 * eight categorical hues cannot be told apart reliably — and there are now more
 * bots than hues, so slots repeat. Every appearance carries glyph + name, with
 * colour as reinforcement only.
 */

export type GlyphName =
  | 'burst'
  | 'descend'
  | 'lock'
  | 'peak'
  | 'target'
  | 'die'
  | 'wall'
  | 'flag'
  | 'shield'
  | 'flame'
  | 'split'
  | 'key'
  | 'probe'
  | 'scales'
  | 'press'
  | 'seat';

export type BotProfile = {
  slug: string;
  tagline: string;
  color: string;
  glyph: GlyphName;
  behaviour: string;
  story: string[];
  /** Shown in place of the record when the bot has never played. */
  unratedNote?: string;
  /** Numbers a bot is actually made of, for the ones worth showing. */
  tables?: {
    title: string;
    note?: string;
    columns: string[];
    rows: string[][];
  }[];
  /** 169 chars, row-major from A down to 2; above the diagonal is suited. */
  range?: string;
  rangeLabel?: string;
  stats: { label: string; value: string }[];
};

export const BOT_PROFILES = profiles as unknown as Record<string, BotProfile>;

/*
 * Ranking order: strongest first, straight from the ledger's Elo. The matrix,
 * the bot pages and the matchup pages all step through this, so "right" means
 * the same thing everywhere -- from the crusher, right is slp-odds, then
 * passive-patty; left from the top wraps to the worst bot in the field.
 *
 * A bot with no rated match yet has no place in the order, so it goes on the
 * end in the roster order data/bots.json lists it in.
 */
export const BOT_ORDER = (() => {
  const rated = [...dashboard.ratings]
    .sort((left, right) => right.elo - left.elo)
    .map((bot) => bot.name)
    .filter((name) => name in BOT_PROFILES);
  const seen = new Set(rated);
  return [
    ...rated,
    ...Object.keys(BOT_PROFILES).filter((slug) => !seen.has(slug)),
  ];
})();

/*
 * One bot lives outside data/bots.json on purpose. It is in no listing, no
 * matrix and no roster count, and it is not at the end of the order either:
 * the arrows have to have walked the whole field once before it is anywhere
 * at all. Landing on the last bot directly does not reveal it.
 */
export const SECRET_SLUG = 'secret';

export const SECRET_BOT: BotProfile = {
  slug: SECRET_SLUG,
  tagline: 'Not in the ledger.',
  color: '#241f1b',
  glyph: 'seat',
  behaviour: 'Unknown.',
  story: [
    'There is one seat this harness cannot fill.',
    'You have already played against it.',
  ],
  unratedNote: 'There is no record.',
  stats: [
    { label: 'Version', value: '—' },
    { label: 'Hands', value: '0' },
    { label: 'Seat', value: 'Occupied' },
  ],
};

export function botNeighbours(slug: string) {
  const count = BOT_ORDER.length;
  if (slug === SECRET_SLUG) {
    return {
      previous: BOT_ORDER[count - 1],
      next: BOT_ORDER[0],
      position: count + 1,
      count,
    };
  }
  const index = BOT_ORDER.indexOf(slug);
  if (index === -1) return { previous: null, next: null, position: 0, count };
  /* A plain ring of the real bots. Whether the last one's next arrow leads
   * out of it is decided in the browser, by how far the arrows have walked. */
  return {
    previous: BOT_ORDER[(index - 1 + count) % count],
    next: BOT_ORDER[(index + 1) % count],
    position: index + 1,
    count,
  };
}

export function botProfile(name: string): BotProfile | undefined {
  return BOT_PROFILES[name];
}

export const RANKS = 'AKQJT98765432';
