import profiles from '@/data/bots.json';

/**
 * Per-bot identity: colour, glyph, and the story each one tells. Bots are named
 * by their slug everywhere -- there are no character names.
 *
 * The data lives in data/bots.json so the React app and the static prototype
 * read the same file and cannot drift. Range strings are generated by driving
 * all 169 hand classes through the compiled bots, not transcribed by hand.
 *
 * Colour is deliberately NOT the identifier. Validated against this surface,
 * eight categorical hues cannot be told apart reliably — and there are now more
 * bots than hues, so slots repeat. Every appearance carries glyph + name, with
 * colour as reinforcement only.
 */

export type GlyphName =
  | 'burst'
  | 'descend'
  | 'lock'
  | 'peak'
  | 'target'
  | 'die'
  | 'wall'
  | 'flag'
  | 'shield'
  | 'flame'
  | 'split'
  | 'key'
  | 'probe';

export type BotProfile = {
  slug: string;
  tagline: string;
  color: string;
  glyph: GlyphName;
  behaviour: string;
  story: string[];
  /** 169 chars, row-major from A down to 2; above the diagonal is suited. */
  range?: string;
  rangeLabel?: string;
  stats: { label: string; value: string }[];
};

export const BOT_PROFILES = profiles as unknown as Record<string, BotProfile>;

/* Roster order, straight from data/bots.json, which is curated by tier:
 * the shove family, then the street-local bots, then the archetypes. The
 * previous/next arrows on a bot page walk this, so it covers every bot
 * whether or not it has played a match yet. */
export const BOT_ORDER = Object.keys(BOT_PROFILES);

export function botNeighbours(slug: string) {
  const index = BOT_ORDER.indexOf(slug);
  if (index === -1) return { previous: null, next: null };
  const count = BOT_ORDER.length;
  return {
    previous: BOT_ORDER[(index - 1 + count) % count],
    next: BOT_ORDER[(index + 1) % count],
    position: index + 1,
    count,
  };
}

export function botProfile(name: string): BotProfile | undefined {
  return BOT_PROFILES[name];
}

export const RANKS = 'AKQJT98765432';
