/* Generated by solvers/push_fold. Do not edit by hand. */
/* 200 bb heads-up shove-or-fold ranges.                 */
/* 40000 Monte Carlo samples per matchup, 20000 iterations. */

#ifndef FELT_PUSH_FOLD_TABLE_H
#define FELT_PUSH_FOLD_TABLE_H

#define FELT_PF_SB_OPEN      1U  /* shove as SB */
#define FELT_PF_BB_VS_LIMP   2U  /* shove over a limp as BB */
#define FELT_PF_BB_VS_ALLIN  4U  /* call an all-in as BB */
#define FELT_PF_BB_VS_SMALL  8U  /* shove over a small raise, <= 3 bb */
#define FELT_PF_BB_VS_MEDIUM 16U /* shove over a larger raise */

/* Index: pairs at rank*13+rank, suited at low*13+high, offsuit at high*13+low. */
static const unsigned char felt_push_fold[169] = {
  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  0,  1,
  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 31,  5,
  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 31,
};

#endif
